// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwgazOgXH1aLsR8zgKtagUrkkGAzk7jE',
    appId: '1:324878215864:web:357cb0e2e43e5ac365e24d',
    messagingSenderId: '324878215864',
    projectId: 'foodfinds-app-287d7',
    authDomain: 'foodfinds-app-287d7.firebaseapp.com',
    databaseURL: 'https://foodfinds-app-287d7-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-app-287d7.appspot.com',
    measurementId: 'G-ST2K3CLRHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RXw2pmEWyaGfaTM3CwyPo5BUjmkkQWc',
    appId: '1:324878215864:android:1a198619193f45b765e24d',
    messagingSenderId: '324878215864',
    projectId: 'foodfinds-app-287d7',
    databaseURL: 'https://foodfinds-app-287d7-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-app-287d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuwTtOQRIE0Q9N_a7dBerqn1evvUrR0NQ',
    appId: '1:324878215864:ios:1740202c02d2833c65e24d',
    messagingSenderId: '324878215864',
    projectId: 'foodfinds-app-287d7',
    databaseURL: 'https://foodfinds-app-287d7-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-app-287d7.appspot.com',
    iosClientId: '324878215864-il795q41easd8hra9edimgggdn9s9c6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodfinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuwTtOQRIE0Q9N_a7dBerqn1evvUrR0NQ',
    appId: '1:324878215864:ios:1740202c02d2833c65e24d',
    messagingSenderId: '324878215864',
    projectId: 'foodfinds-app-287d7',
    databaseURL: 'https://foodfinds-app-287d7-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-app-287d7.appspot.com',
    iosClientId: '324878215864-il795q41easd8hra9edimgggdn9s9c6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodfinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiwgazOgXH1aLsR8zgKtagUrkkGAzk7jE',
    appId: '1:324878215864:web:829e5dc6d00bb79565e24d',
    messagingSenderId: '324878215864',
    projectId: 'foodfinds-app-287d7',
    authDomain: 'foodfinds-app-287d7.firebaseapp.com',
    databaseURL: 'https://foodfinds-app-287d7-default-rtdb.firebaseio.com',
    storageBucket: 'foodfinds-app-287d7.appspot.com',
    measurementId: 'G-KFNC4BVQHZ',
  );
}
